name: SchematicsExtended
version: @version@
main: net.islandearth.schematicsextended.SchematicsExtended
api-version: 1.13
load: STARTUP
authors: [SamB440, brainsynder, Math0424]
description: Build schematics block-by-block!
website: https://gitlab.com/SamB440/Schematics-Extended
